// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using excellentsoftwares_short_url.app.Migrations;

namespace es_url_shortner.data_access.Migrations
{
    [DbContext(typeof(url_shortnerContext))]
    partial class url_shortnerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("es_url_shortner.data_access.Model.Domain.LinksDatum", b =>
                {
                    b.Property<int>("LinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DestinationUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DomainUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LinkId");

                    b.ToTable("LinksData");
                });

            modelBuilder.Entity("es_url_shortner.data_access.Model.Domain.QR", b =>
                {
                    b.Property<int>("qrId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("qrStr")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("qrId");

                    b.ToTable("QRCodesUri");
                });

            modelBuilder.Entity("es_url_shortner.data_access.Model.Domain.User", b =>
                {
                    b.Property<int>("srno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("srno")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<bool>("isCaptchaEnable")
                        .IsUnicode(false)
                        .HasColumnType("bit")
                        .HasColumnName("isCaptchaEnable");

                    b.Property<string>("password")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("password");

                    b.Property<string>("phoneNo")
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("phoneNo");

                    b.Property<string>("uName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("uName");

                    b.Property<string>("userId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("userId");

                    b.HasKey("srno");

                    b.ToTable("user_table");
                });
#pragma warning restore 612, 618
        }
    }
}
